version: '3'

services:
  # React App
  nvidia-client:
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    command: pnpm start-client
    ports:
      - 4200:4200
    depends_on:
      - nvidia-api
    

  # Express App
  nvidia-api:
    environment:
      - DATABASE_URL=mongodb://mongo:27017/nvidia
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    command: pnpm start-api
    ports:
      - 3333:3333
      - 4311:4311
    depends_on:
      - mongo
  
  # MongoDB
  mongo:
    extends:
      file: docker-compose.db.yml
      service: mongo

volumes:
  mono-node-modules: null