version: '3'

services:
  mongo:
    build:
      context: .
      dockerfile: docker/DockerFile.db
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_DB: nvidia
      MONGO_COLLECTION: mnf_data
    volumes:
      - ./docker/mongo_export.tar.gz:/dump/mongo_export.tar.gz
