version: '3'

services:
  # React App
  nvidia-client:
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    command: pnpm start-client
    ports:
      - 4201:4200

  # Express App
  nvidia-api:
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    command: pnpm start-api
    ports:
      - 3333:3333
      - 4311:4311

volumes:
  mono-node-modules: null